config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'lists#index'

  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
 
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    @bookmarks = Bookmark.all
  end

  def show
    @bookmark = Bookmark.find(params[:list_id])
  end

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path(@list)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>

app/views/bookmarks/index.html.erb
<h1>All Bookmarks:</h1>


<table class="table">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

</table>
<div class="card">
  <p>
    <% @bookmarks.each do |bookmark| %>
      <li><%= link_to bookmark.name, bookmark_path(bookmark) %></li>
    <% end %>
  </p>

  <%= link_to "New bookmark", new_bookmark_path  %>
</div>

app/views/bookmarks/new.html.erb
<%= render "bookmarks/form", bookmark: @bookmark, list: @list %>

app/views/bookmarks/show.html.erb
<h2><%= @bookmark.name %></h2>

<%= link_to "Back", bookmarks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/lists/index.html.erb
<h1>All lists:</h1>
    <% @lists.each do |list| %>
      <li><%= link_to list.name, list_path(list) %></li>
    <% end %>
</p>


<%= link_to "New list", new_list_path, class: 'btn btn-primary' %>
</table>

app/views/lists/new.html.erb
<%= render "lists/form", list: @list %>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>

<%= link_to "Back", lists_path %>

<p><strong>Bookmarks</strong></p>

<div class="row my-2">

  <% @list.movies.each do |movie| %>
    <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
    <div class="col-12 col-sm-4" style="width: 18rem;">
      <div class="bg-white rounded shadow h-100 d-flex flex-column justify-content-between">
        <%= image_tag movie.poster_url, alt: movie.title, class: 'card-img-top movie-img rounded-top w-100' %>
        <p class="card-title"><%= movie.title %> <%= movie.rating %></p>
        <p><%= movie.overview %></p>
        <p><%= bookmark.comment %></p>
      </div>
    </div>
  <% end %>
</div>
<br>

<%= link_to 'Add a movie to your list', new_list_bookmark_path(@list), class: 'btn btn-primary' %>
<%= link_to 'Delete this list', list_path(@list), class: 'btn btn-danger text-white', data: { turbo_confirm: 'Are you sure you want to delete this list?', turbo_method: :delete } %>